In [1]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#Craete  a dataframe
df=pd.read_csv("E:\dataset\car.csv")
df

userid  gender  age  income  purchase
0   123456780    male   19   19000         0
1   123456781    male   25   20000         0
2   123456782  female   26   43000         0
3   123456783  female   27   57000         0
4   123456784    male   19   76000         0
5   123456785    male   27   58000         0
6   123456786  female   27   84000         0
7   123456787  female   32  190000         1
8   123456788    male   25   33000         0
9   123456789  female   35   65000         0
10  123456790  female   26   80000         0
11  123456791  female   26   25000         0
12  123456792    male   20   26000         0

In [3]:
#Choose X and y
X = df.iloc[:, [2, 3]].values
y = df.iloc[:, 4].values

In [4]:
print(X)

[[    19  19000]
 [    25  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 190000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  25000]
 [    20  26000]]


In [5]:
print(y)

[0 0 0 0 0 0 0 1 0 0 0 0 0]


In [6]:
#Split our dataframe into training and testing data
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.25,random_state = 0)

In [8]:
print(X_test)

[[   27 84000]
 [   26 25000]
 [   19 76000]
 [   26 80000]]


In [9]:
print(y_test)

[0 0 0 0]


In [10]:
#Perform scaling operation
from sklearn.preprocessing import StandardScaler
 
obj = StandardScaler()
 
X_train = obj.fit_transform(X_train)
 
X_test = obj.transform(X_test)

In [11]:
print(X_test)

[[ 0.16274669  0.5468859 ]
 [-0.04649906 -0.63840558]
 [-1.5112193   0.38616841]
 [-0.04649906  0.46652716]]


In [12]:
#Create LogisticRegression Model
from sklearn.linear_model import LogisticRegression
 
model = LogisticRegression()

In [13]:
#Trained the model
model.fit(X_train,y_train)

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [14]:
#Predict 
y_pred=model.predict(X_test)
y_pred

array([0, 0, 0, 0], dtype=int64)

In [15]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

1.0
